version: 2.1

executors:
  clojure-node:
    working_directory: ~/app
    docker:
      - image: circleci/clojure:lein-2.10.0
        environment:
          JVM_OPTS: -Xmx2g
          LEIN_ROOT: true
      - image: circleci/node:16-browsers
      - image: eclipse-temurin:17-jdk-jammy
      - image: node:19-6-alpine
    shell: /bin/bash

jobs:
  build:
    executor: clojure-node
    steps:
      - checkout
      - run: sudo apt-get install nodejs
      - run: sudo apt-get install npm
      - run: node -v
      - run: npm -v
      - run: npm install shadow-cljs
      - run: lein deps
      - run: npx shadow-cljs release app
      - run: lein uberjar
      - persist_to_workspace:
          root: ~/app
          paths:
            - target

  build-docker:
    executor: clojure-node
    steps:
      - attach_workspace:
          at: ~/app
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp:${CIRCLE_SHA1} .
            docker tag myapp:${CIRCLE_SHA1} myapp:latest
      - run:
          name: Push Docker image to registry
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push myapp:${CIRCLE_SHA1}
            docker push myapp:latest